# Generated by Django 4.1.7 on 2024-04-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_skills', models.CharField(max_length=400)),
                ('p_details', models.CharField(max_length=1000)),
            ],
        ),
    ]
